### ISSUE TITLE
on linux, darwin module is being installed.

### ISSUE THREAD

**Issue by collinanderson** [mapbox/node-srs#52]
On linux, we should be getting `node_modules/srs/lib/binding/node-v11-linux-x64/srs.node`, but we're instead getting `node_modules/srs/lib/binding/node-v14-darwin-x64/srs.node`.

Anything we can do to debug this? Why is it installing a mac binary on linux?

**Comment by springmeyer** [comment]
The only cause for this would be if you passed `--target_platform=darwin` (per https://github.com/mapbox/node-pre-gyp#options) or if you installed originally on linux and then copied the `node_modules` folder. Either way this is not a node-srs issue, and surely something to do with user install steps.
